version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "ruby:bundler"
    directory: "/android"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: "ruby:bundler"
    directory: "/ios"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
